name: 01- Building blocks

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Hello
              run: echo "Hello, World!"
            - name: Echo Hello
              run: |
                echo "Hello, World!"
                echo "This is a multi-line echo command."
    

