name: 01- Building blocks

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Hello
              run: echo "Hello, World!"
            - name: Echo OS
              run: |
                echo "Checking the operating system..."
                echo "Running on: $RUNNER_OS"
    

